Попытка пройти тесты
js-tasks-ru/js-20200622_bostonov pull request #13
Opened 2020-06-29 05:09 UTC by aibread

2020-06-29 05:15 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings
+ should correctly sort language-specific characters
+ should correctly sort strings started from uppercase
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-06-30 10:09 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +export function sortStrings(arr, param = 'asc') {
данное решение НЕ принимается

2020-06-30 10:09 UTC, dosandk requested changes
пожалуйста посмотрите на решения которые мы разбирали на занятии и внесите изменения в Ваш PR

2020-07-01 10:57 UTC, jsru commented
@dosandk ping :)

2020-07-01 11:40 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +export function sortStrings(arr, param = 'asc') {
исправлено - good 👍

2020-07-01 11:41 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let elements = Object.entries(obj);
нет необходимости создавать лишние переменные и переприсваивать их
действуйте так:
```
const elements = Object.entries(obj).filter(([key]) => fields.includes(key));

return Object.fromEntries(elements);
```

2020-07-01 11:41 UTC, dosandk approved these changes
решения принимаются, посмотрите пожалуйста комментарии :mag:

2020-07-01 11:41 UTC, merged