SortableTable компонент - без обработчиков событий клика и динамической загрузки
js-tasks-ru/js-20200622_bostonov pull request #17
Opened 2020-07-12 09:08 UTC by aibread

2020-07-12 09:14 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-07-12 13:02 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    const element = document.createElement('div');
было бы неплохо эту логику поместить в `render`

2020-07-12 13:06 UTC, dosandk requested changes
В компоненте NotificationMassege необходимо устранить логику обращения к DOM с целью узнать есть ли предыдущий компонент в DOM

2020-07-12 13:06 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    <div class="notification ${this.type}" style="--value:20s">
`20s` - это динамический параметр, используйте значение `duration`

2020-07-12 13:06 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (parent !== undefined) {
можно сократить проверку 
```
if (!parent)
```

2020-07-12 13:06 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show(parent) {
используйте силу параметров по умолчанию, это позволит избавиться от лишних `if`

```
show(parent = document.body)
```

2020-07-12 13:06 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    const element = document.getElementsByClassName('notification')[0];
не стоит обращаться к DOM чтобы понять что предыдущий компонент все еще там есть

2020-07-12 13:06 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
>  export default class SortableTable {
good 👍

2020-07-13 15:25 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 06-events-practice/2-tooltip/index.spec.js — изменен
```

2020-07-13 15:58 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort 'asc' correctly for 'sortType' equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
- should sort 'asc' correctly for 'sortType' equal string
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

2020-07-15 10:05 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.render();
было бы неплохо рендерить уже отсортированные данные, сейчас судя по коду происходит рендер, а уже после вызывается метод `sort` и изменяется `body` таблицы
другими словами - сортировку нужно сделать до рендера

2020-07-15 10:06 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  // constructor() {
не оставляйте в PR закомментированный код
Если что-то комментируете - добавьте TODO с пояснением - почему закомментировано

2020-07-15 10:06 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    if (event.target.dataset.tooltip != undefined) {
`!=` - нет такого оператора в JS

2020-07-15 10:07 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      if (elem !== null) {
можно упростить логику в этом методе, подумайте как

2020-07-15 10:08 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.removeEventListener('pointerover', this.pointerOverHandler);
ох, тут что-то не то происходит
1 - Синглтон не получился
2 - обработчики выносим в отдельный метод
3 - снятие обработчиков не может быть в том же методе что и навешивание

2020-07-15 10:09 UTC, dosandk requested changes
Необходимо исправить логику Tooltip в навешивании обработчиков событий

2020-07-19 09:56 UTC, jsru commented
@dosandk ping :)

2020-07-19 11:37 UTC, dosandk approved these changes
good 👍

2020-07-19 11:37 UTC, merged